# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm
  
hydra:
  launcher:
    partition: my_partition
    cpus_per_task: 1
    gres: null
    timeout_min: 60
    mem_gb: 10
    setup:
      - export JAX_PLATFORM_NAME=cpu
