defaults:
  - _self_
  - algorithm: ppo
  - environment: contextual_minigrid
  - search_space: ppo
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# General setup
runner: standard
debug: false
seed: 0
output_dir: runs
wandb_project: null
tensorboard_file: null
experiment_name: domain_randomization/${env}/seed

hydra:
  run:
    dir: ${output_dir}/${experiment_name}_${seed}
  sweep:
    dir: ${output_dir}/${experiment_name}_${seed}

# Training
eval_every_n_steps: 1e4  # After how many steps to evaluate.
n_episodes_eval: 10
checkpoint: null  # Path to load model checkpoint
save_model_every_n_steps: 5e5

# Add domain randomization curriculum
algorithm_kwargs: 
  meta_methods: 
    - mighty_domain_randomization.mighty_syllabus_dr.MightySyllabusDR
  meta_kwargs: 
    - curriculum_config:
        curriculum_kwargs:
          batch_size: ${num_envs}  # Get n_envs from environment config


