defaults:
  - _self_
  - /cluster: cpu
  - algorithm: ppo
  - environment: contextual_minigrid
  - search_space: ppo
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/sweeper: HyperSMAC

# General setup
runner: standard
debug: false
seed: 0
output_dir: hpo
wandb_project: null
tensorboard_file: null
experiment_name: hpo_base_algorithm/${env}
algorithm_kwargs: {}

# Training
eval_every_n_steps: 1e4  # After how many steps to evaluate.
n_episodes_eval: 20
checkpoint: null  # Path to load model checkpoint
save_model_every_n_steps: 5e5

# Add HPO settings
hydra:
  sweeper:
    n_trials: 32
    sweeper_kwargs:
      maximize: true
      seeds: [0, 1, 2]
      optimizer_kwargs:
        smac_facade: 
          _target_: smac.facade.blackbox_facade.BlackBoxFacade
          _partial_: true
          logging_level: 20  # 10 DEBUG, 20 INFO
        scenario:
          seed: 42
          n_trials: ${hydra.sweeper.n_trials}
          deterministic: true
          output_directory: ${hydra.sweep.dir}
    search_space: ${search_space}
  run:
    dir: ${output_dir}/${experiment_name}_${seed}
  sweep:
    dir: ${output_dir}/${experiment_name}_${seed}